on:
  push:
    branches:
      - main
name: docs

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
          # Give the default GITHUB_TOKEN write permission to commit and push the
          # added or changed files to the repository.
          contents: write
    steps:
      - uses: actions/checkout@v3
      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: doppler-nvim-docs
          version: "Neovim >= 0.8.0"
          demojify: true
          treesitter: true
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "auto-generate vimdoc"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"

